// Generated by CoffeeScript 1.7.1
var DataNotJsonParsableError, DataNotStringError, MalformedDataError, MalformedSchemaError, NotEnoughDataError, NotValidatableError, SchemaNotJsonParsableError, UnknownValidatorError,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

MalformedDataError = (function(_super) {
  __extends(MalformedDataError, _super);

  function MalformedDataError() {
    return MalformedDataError.__super__.constructor.apply(this, arguments);
  }

  return MalformedDataError;

})(Error);

DataNotJsonParsableError = (function(_super) {
  __extends(DataNotJsonParsableError, _super);

  function DataNotJsonParsableError() {
    return DataNotJsonParsableError.__super__.constructor.apply(this, arguments);
  }

  return DataNotJsonParsableError;

})(MalformedDataError);

DataNotStringError = (function(_super) {
  __extends(DataNotStringError, _super);

  function DataNotStringError() {
    return DataNotStringError.__super__.constructor.apply(this, arguments);
  }

  return DataNotStringError;

})(MalformedDataError);

MalformedSchemaError = (function(_super) {
  __extends(MalformedSchemaError, _super);

  function MalformedSchemaError() {
    return MalformedSchemaError.__super__.constructor.apply(this, arguments);
  }

  return MalformedSchemaError;

})(Error);

SchemaNotJsonParsableError = (function(_super) {
  __extends(SchemaNotJsonParsableError, _super);

  function SchemaNotJsonParsableError() {
    return SchemaNotJsonParsableError.__super__.constructor.apply(this, arguments);
  }

  return SchemaNotJsonParsableError;

})(MalformedSchemaError);

UnknownValidatorError = (function(_super) {
  __extends(UnknownValidatorError, _super);

  function UnknownValidatorError() {
    return UnknownValidatorError.__super__.constructor.apply(this, arguments);
  }

  return UnknownValidatorError;

})(Error);

NotValidatableError = (function(_super) {
  __extends(NotValidatableError, _super);

  function NotValidatableError() {
    return NotValidatableError.__super__.constructor.apply(this, arguments);
  }

  return NotValidatableError;

})(Error);

NotEnoughDataError = (function(_super) {
  __extends(NotEnoughDataError, _super);

  function NotEnoughDataError() {
    return NotEnoughDataError.__super__.constructor.apply(this, arguments);
  }

  return NotEnoughDataError;

})(Error);

module.exports = {
  DataNotJsonParsableError: DataNotJsonParsableError,
  SchemaNotJsonParsableError: SchemaNotJsonParsableError,
  MalformedSchemaError: MalformedSchemaError,
  MalformedDataError: MalformedDataError,
  UnknownValidatorError: UnknownValidatorError,
  DataNotStringError: DataNotStringError,
  NotValidatableError: NotValidatableError,
  NotEnoughDataError: NotEnoughDataError
};
